<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Customer;

class CustomerSeeder extends Seeder
{
    public function run(): void
    {
        $customers = [
            [
                'customer_id' => 'CUST001',
                'name' => 'Rahul Sharma',
                'phone_number' => '+91 98765 43210',
                'date_of_birth' => '1990-05-15',
                'gender' => 'male',
                'hobby_1' => 'Reading',
                'hobby_2' => 'Cricket',
                'hobby_3' => 'Cooking',
                'favorite_food' => 'Biryani',
                'profession' => 'Software Engineer',
                'religion' => 'Hinduism',
                'recommended_by' => 'Priya Patel',
                'number_of_children' => 2,
                'residential_district' => 'Mumbai',
                'consent_scholarship' => true,
                'consent_whatsapp' => true,
                'membership_date' => '2024-01-15',
                'status' => 'active',
            ],
            [
                'customer_id' => 'CUST002',
                'name' => 'Priya Patel',
                'phone_number' => '+91 87654 32109',
                'date_of_birth' => '1988-08-22',
                'gender' => 'female',
                'hobby_1' => 'Dancing',
                'hobby_2' => 'Yoga',
                'hobby_3' => 'Painting',
                'favorite_food' => 'Pasta',
                'profession' => 'Teacher',
                'religion' => 'Hinduism',
                'recommended_by' => 'Amit Kumar',
                'number_of_children' => 1,
                'residential_district' => 'Delhi',
                'consent_scholarship' => true,
                'consent_whatsapp' => false,
                'membership_date' => '2024-02-10',
                'status' => 'active',
            ],
            [
                'customer_id' => 'CUST003',
                'name' => 'Amit Kumar',
                'phone_number' => '+91 76543 21098',
                'date_of_birth' => '1992-03-10',
                'gender' => 'male',
                'hobby_1' => 'Gym',
                'hobby_2' => 'Music',
                'hobby_3' => 'Travel',
                'favorite_food' => 'Pizza',
                'profession' => 'Doctor',
                'religion' => 'Hinduism',
                'recommended_by' => 'Neha Singh',
                'number_of_children' => 0,
                'residential_district' => 'Bangalore',
                'consent_scholarship' => false,
                'consent_whatsapp' => true,
                'membership_date' => '2024-03-05',
                'status' => 'active',
            ],
            [
                'customer_id' => 'CUST004',
                'name' => 'Neha Singh',
                'phone_number' => '+91 65432 10987',
                'date_of_birth' => '1995-12-08',
                'gender' => 'female',
                'hobby_1' => 'Shopping',
                'hobby_2' => 'Photography',
                'hobby_3' => 'Baking',
                'favorite_food' => 'Chocolate Cake',
                'profession' => 'Designer',
                'religion' => 'Sikhism',
                'recommended_by' => 'Raj Malhotra',
                'number_of_children' => 0,
                'residential_district' => 'Hyderabad',
                'consent_scholarship' => true,
                'consent_whatsapp' => true,
                'membership_date' => '2024-01-20',
                'status' => 'active',
            ],
            [
                'customer_id' => 'CUST005',
                'name' => 'Raj Malhotra',
                'phone_number' => '+91 54321 09876',
                'date_of_birth' => '1985-07-14',
                'gender' => 'male',
                'hobby_1' => 'Golf',
                'hobby_2' => 'Wine Tasting',
                'hobby_3' => 'Cooking',
                'favorite_food' => 'Butter Chicken',
                'profession' => 'Business Owner',
                'religion' => 'Hinduism',
                'recommended_by' => 'Sunita Reddy',
                'number_of_children' => 3,
                'residential_district' => 'Chennai',
                'consent_scholarship' => true,
                'consent_whatsapp' => true,
                'membership_date' => '2024-02-28',
                'status' => 'active',
            ],
            [
                'customer_id' => 'CUST006',
                'name' => 'Sunita Reddy',
                'phone_number' => '+91 43210 98765',
                'date_of_birth' => '1987-11-30',
                'gender' => 'female',
                'hobby_1' => 'Gardening',
                'hobby_2' => 'Reading',
                'hobby_3' => 'Meditation',
                'favorite_food' => 'Dosa',
                'profession' => 'Accountant',
                'religion' => 'Hinduism',
                'recommended_by' => 'Vikram Mehta',
                'number_of_children' => 2,
                'residential_district' => 'Kolkata',
                'consent_scholarship' => false,
                'consent_whatsapp' => true,
                'membership_date' => '2024-03-15',
                'status' => 'inactive',
            ],
            [
                'customer_id' => 'CUST007',
                'name' => 'Vikram Mehta',
                'phone_number' => '+91 32109 87654',
                'date_of_birth' => '1993-04-25',
                'gender' => 'male',
                'hobby_1' => 'Cricket',
                'hobby_2' => 'Swimming',
                'hobby_3' => 'Chess',
                'favorite_food' => 'Pav Bhaji',
                'profession' => 'Engineer',
                'religion' => 'Jainism',
                'recommended_by' => 'Anjali Desai',
                'number_of_children' => 1,
                'residential_district' => 'Pune',
                'consent_scholarship' => true,
                'consent_whatsapp' => false,
                'membership_date' => '2024-01-08',
                'status' => 'active',
            ],
            [
                'customer_id' => 'CUST008',
                'name' => 'Anjali Desai',
                'phone_number' => '+91 21098 76543',
                'date_of_birth' => '1991-09-18',
                'gender' => 'female',
                'hobby_1' => 'Dancing',
                'hobby_2' => 'Singing',
                'hobby_3' => 'Cooking',
                'favorite_food' => 'Gulab Jamun',
                'profession' => 'Marketing Manager',
                'religion' => 'Hinduism',
                'recommended_by' => 'Rahul Sharma',
                'number_of_children' => 0,
                'residential_district' => 'Ahmedabad',
                'consent_scholarship' => true,
                'consent_whatsapp' => true,
                'membership_date' => '2024-02-12',
                'status' => 'active',
            ],
            [
                'customer_id' => 'CUST009',
                'name' => 'Karan Johar',
                'phone_number' => '+91 10987 65432',
                'date_of_birth' => '1989-06-12',
                'gender' => 'male',
                'hobby_1' => 'Movies',
                'hobby_2' => 'Photography',
                'hobby_3' => 'Travel',
                'favorite_food' => 'Biryani',
                'profession' => 'Film Director',
                'religion' => 'Hinduism',
                'recommended_by' => 'Priya Patel',
                'number_of_children' => 1,
                'residential_district' => 'Mumbai',
                'consent_scholarship' => false,
                'consent_whatsapp' => true,
                'membership_date' => '2024-03-01',
                'status' => 'inactive',
            ],
            [
                'customer_id' => 'CUST010',
                'name' => 'Zara Khan',
                'phone_number' => '+91 09876 54321',
                'date_of_birth' => '1994-02-28',
                'gender' => 'female',
                'hobby_1' => 'Fashion',
                'hobby_2' => 'Makeup',
                'hobby_3' => 'Shopping',
                'favorite_food' => 'Kebab',
                'profession' => 'Fashion Designer',
                'religion' => 'Islam',
                'recommended_by' => 'Amit Kumar',
                'number_of_children' => 0,
                'residential_district' => 'Jaipur',
                'consent_scholarship' => true,
                'consent_whatsapp' => true,
                'membership_date' => '2024-01-25',
                'status' => 'active',
            ],
        ];

        foreach ($customers as $customer) {
            Customer::create($customer);
        }
    }
}
