<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\StationaryItem;

class StationaryItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $items = [
            [
                'name' => 'Pencil',
                'article' => 'PENCIL-2B',
                'quality' => 'Premium',
                'color' => 'Black',
                'company' => 'Dux',
                'size' => 'Standard',
                'volume' => '10g',
                'shape' => 'Round',
                'cte_reck_number' => 'CTE001',
                'unit_cost' => 5.00,
                'selling_price' => 8.00,
                'profit_margin' => 3.00,
                'min_stock_level' => 50,
                'expiry_date' => null,
                'status' => 'active',
                'description' => 'High-quality 2B pencils for writing and drawing',
            ],
            [
                'name' => 'Ball Pen',
                'article' => 'BALLPEN-BLUE',
                'quality' => 'Standard',
                'color' => 'Blue',
                'company' => 'ORO',
                'size' => 'Standard',
                'volume' => '15ml',
                'shape' => 'Cylindrical',
                'cte_reck_number' => 'CTE002',
                'unit_cost' => 12.00,
                'selling_price' => 20.00,
                'profit_margin' => 8.00,
                'min_stock_level' => 30,
                'expiry_date' => null,
                'status' => 'active',
                'description' => 'Smooth writing ball pens with blue ink',
            ],
            [
                'name' => 'Notebook',
                'article' => 'NOTEBOOK-A4',
                'quality' => 'Premium',
                'color' => 'White',
                'company' => 'Piano',
                'size' => 'A4',
                'volume' => '100 pages',
                'shape' => 'Rectangular',
                'cte_reck_number' => 'CTE003',
                'unit_cost' => 25.00,
                'selling_price' => 40.00,
                'profit_margin' => 15.00,
                'min_stock_level' => 20,
                'expiry_date' => null,
                'status' => 'active',
                'description' => 'High-quality A4 notebooks with ruled pages',
            ],
            [
                'name' => 'Eraser',
                'article' => 'ERASER-WHITE',
                'quality' => 'Standard',
                'color' => 'White',
                'company' => 'Dux',
                'size' => 'Medium',
                'volume' => '5g',
                'shape' => 'Rectangular',
                'cte_reck_number' => 'CTE004',
                'unit_cost' => 3.00,
                'selling_price' => 6.00,
                'profit_margin' => 3.00,
                'min_stock_level' => 40,
                'expiry_date' => null,
                'status' => 'active',
                'description' => 'Soft white erasers for clean erasing',
            ],
            [
                'name' => 'Sharpener',
                'article' => 'SHARPENER-DUAL',
                'quality' => 'Premium',
                'color' => 'Blue',
                'company' => 'ORO',
                'size' => 'Standard',
                'volume' => '8g',
                'shape' => 'Rectangular',
                'cte_reck_number' => 'CTE005',
                'unit_cost' => 8.00,
                'selling_price' => 15.00,
                'profit_margin' => 7.00,
                'min_stock_level' => 25,
                'expiry_date' => null,
                'status' => 'active',
                'description' => 'Dual-hole pencil sharpener with container',
            ],
            [
                'name' => 'Ruler',
                'article' => 'RULER-30CM',
                'quality' => 'Standard',
                'color' => 'Transparent',
                'company' => 'Piano',
                'size' => '30cm',
                'volume' => '12g',
                'shape' => 'Rectangular',
                'cte_reck_number' => 'CTE006',
                'unit_cost' => 10.00,
                'selling_price' => 18.00,
                'profit_margin' => 8.00,
                'min_stock_level' => 20,
                'expiry_date' => null,
                'status' => 'active',
                'description' => 'Transparent plastic ruler with centimeter markings',
            ],
            [
                'name' => 'Glue Stick',
                'article' => 'GLUE-20G',
                'quality' => 'Standard',
                'color' => 'White',
                'company' => 'Dux',
                'size' => 'Standard',
                'volume' => '20g',
                'shape' => 'Cylindrical',
                'cte_reck_number' => 'CTE007',
                'unit_cost' => 15.00,
                'selling_price' => 25.00,
                'profit_margin' => 10.00,
                'min_stock_level' => 15,
                'expiry_date' => '2026-12-31',
                'status' => 'active',
                'description' => 'Non-toxic glue stick for paper and cardboard',
            ],
            [
                'name' => 'Scissors',
                'article' => 'SCISSORS-8INCH',
                'quality' => 'Premium',
                'color' => 'Silver',
                'company' => 'ORO',
                'size' => '8 inch',
                'volume' => '45g',
                'shape' => 'Scissor',
                'cte_reck_number' => 'CTE008',
                'unit_cost' => 35.00,
                'selling_price' => 60.00,
                'profit_margin' => 25.00,
                'min_stock_level' => 10,
                'expiry_date' => null,
                'status' => 'active',
                'description' => 'Stainless steel scissors for cutting paper and fabric',
            ],
            [
                'name' => 'Stapler',
                'article' => 'STAPLER-MINI',
                'quality' => 'Standard',
                'color' => 'Black',
                'company' => 'Piano',
                'size' => 'Mini',
                'volume' => '30g',
                'shape' => 'Rectangular',
                'cte_reck_number' => 'CTE009',
                'unit_cost' => 45.00,
                'selling_price' => 75.00,
                'profit_margin' => 30.00,
                'min_stock_level' => 8,
                'expiry_date' => null,
                'status' => 'active',
                'description' => 'Mini stapler for small documents',
            ],
            [
                'name' => 'Highlighter',
                'article' => 'HIGHLIGHTER-YELLOW',
                'quality' => 'Standard',
                'color' => 'Yellow',
                'company' => 'Dux',
                'size' => 'Standard',
                'volume' => '8ml',
                'shape' => 'Cylindrical',
                'cte_reck_number' => 'CTE010',
                'unit_cost' => 18.00,
                'selling_price' => 30.00,
                'profit_margin' => 12.00,
                'min_stock_level' => 20,
                'expiry_date' => '2026-06-30',
                'status' => 'active',
                'description' => 'Fluorescent yellow highlighter for marking text',
            ],
        ];

        foreach ($items as $item) {
            StationaryItem::create($item);
        }
    }
}
